### ISSUE TITLE
Is the method "ready" not required any more?

### ISSUE THREAD

**Issue by leon** [tuananh/camaro#102]
the "ready" function is no longer exported in version 5.0.0 
does that mean that we don't need to call it, or that you missed exporting it?

**Comment by leon** [comment]
I tried it without `ready` and it's telling me

"camaro is not yet initialized. You need to call `ready()` first."

So I think you need to export the function :)

**Comment by tuananh** [comment]
@leon the method `ready` is new in v5. it is exported https://github.com/tuananh/camaro/blob/develop/index.js#L79

**Comment by tuananh** [comment]
Closed in #104
