### ISSUE TITLE
Suggestion: Add `engines` field to package.json

### ISSUE THREAD

**Issue by jonsherrard** [tuananh/camaro#108]
**Describe the bug**
Camaro requires Node >= 12 to run, installs quietly into <12 projects and creates phantom bugs.

by adding:

```json
"engines": {
  "node": ">=12.0.0"
}
```

A compatible node version will be verified at install time, triggering a failure if necessary.

**Comment by tuananh** [comment]
Fixed in b5a8e12f3a8771beca7b84103a31a9c9075e5060
