### ISSUE TITLE
Question: Template extraction

### ISSUE THREAD

**Issue by jonsherrard** [tuananh/camaro#109]
Hi There!

Thanks again for Camaro. It's so lovely, but unfortunately I have to work in a Node 10 environment. 

I wonder if in your travels you've come across any libraries that use a similar XPath template API. that Camaro uses, or is it uniquely your design? 

Thank you for being so generous with your time!

**Comment by tuananh** [comment]
Hi,

`worker_threads` in Node 10 is experimental behind a flag `--experimental-worker`. You can try to see if it works for you by running `node --experimental-worker index.js`

> I wonder if in your travels you've come across any libraries that use a similar XPath template API. that Camaro uses, or is it uniquely your design?

I'm aware of another project that does the transformation in a pretty unique way: cruftless. I do mention about it here https://github.com/tuananh/camaro#similar-projects

However, their template is not xpath base.
