### ISSUE TITLE
Warning: (node:23080) ExperimentalWarning: The ESM module loader is experimental.

### ISSUE THREAD

**Issue by ironcladmerc** [tuananh/camaro#111]
Camaro started giving this warning recently, it still works, though. 

Running on node.js 12.18.0 and camaro is v6.0.2.  

Is this something a new version of node introduced or a new version of camaro? 

(node:23080) ExperimentalWarning: The ESM module loader is experimental.
(node:23080) ExperimentalWarning: The ESM module loader is experimental.
(node:23080) ExperimentalWarning: The ESM module loader is experimental.
(node:23080) ExperimentalWarning: The ESM module loader is experimental.

**Comment by tuananh** [comment]
it's probably due to sth `piscina`, a dependency camaro is using. each time it's log due to a worker thread is spawn, same as no. of cpu core i assume (the default setting)
