### ISSUE TITLE
Question: custom template

### ISSUE THREAD

**Issue by marehem** [tuananh/camaro#114]
Please, I need to perform some logic while transforming from XML. for example, I need to map XML value if 0 to some text value in output JSON like 'ZERO' and if 1 output "ONE' in JSON.

if please you can provide an example of how to call a function within the template block to run such logic while doing the tranformation.

**Comment by tuananh** [comment]
@marehem right now it's not possible to define custom logic. it's limited to xpath functions only.

**Comment by marehem** [comment]
thanks
