### ISSUE TITLE
Dependencies not found (6.0.2)

### ISSUE THREAD

**Issue by alsatianio** [tuananh/camaro#115]
Not sure what's happening here, or if it's just my Node, but every time I try to run my build after installing Camaro, I get the following:

```
ERROR  Failed to compile with 4 errors               

These dependencies were not found:       

* async_hooks in ./node_modules/eventemitter-asyncresource/dist/src/index.js, ./node_modules/piscina/dist/src/index.js
* perf_hooks in ./node_modules/piscina/dist/src/index.js
* worker_threads in ./node_modules/piscina/dist/src/index.js    
```

**Comment by tuananh** [comment]
@alsatianio what node version you're using?

**Comment by alsatianio** [comment]
@tuananh 14.4.0, but I've tried 8, 10, and 12 as well.

**Comment by tuananh** [comment]
@alsatianio it's weird. all those libs are builtin library of node.

**Comment by alsatianio** [comment]
@tuananh For some reason it only happens with Camaro. No other packages are throwing the error, or have ever thrown that error.

**Comment by alsatianio** [comment]
@tuananh Seems like it's got something to do with Nuxt.js, investigating further.

**Comment by tuananh** [comment]
@alsatianio ah, camaro is currently not usable for web. it's sth to do with the breaking changes i did in v6.

you can use v4 or v5 if it's intended for the web.

**Comment by alsatianio** [comment]
Thanks @tuananh !
