### ISSUE TITLE
Unable to parse input with invalid characters

### ISSUE THREAD

**Issue by curbengh** [tuananh/camaro#118]
**Describe the bug**
Unable to parse input with unprintable characters.

**Minimal Script To Reproduce**

There are two unprintable/invalid characters in between `foo` and `bar`, since I couldn't paste the characters here, refer to [test.js.zip](https://github.com/tuananh/camaro/files/5148594/test.js.zip). If the attachment doesn't include those characters (I might've saved it incorrectly), refer to L20136 and L25599 of [this attachment](https://github.com/hexojs/hexo-migrator-wordpress/issues/105#issuecomment-683415042).

Current behaviour is that `sample.wp` is undefined.

``` js
const { transform } = require('camaro');

const detectFeedType = async () => {
  const xml = '<rss>foobar</rss>'
  const sample = await transform(xml, {
    wp: 'rss'
  });

  if (sample.wp) console.log(sample.wp);
  else console.log('invalid')
};
detectFeedType()
```

**Expected behavior**
Ignore those characters and outputs `foobar`.

**Screenshots**
![invalid-char](https://user-images.githubusercontent.com/43627182/91688657-a04ec400-eba1-11ea-9c3f-1f439cfaec87.png)

- camaro version: 6.0.3
- Node version: 14.8.0
- Operating system: Solus

**Comment by tuananh** [comment]
@curbengh when i open test.js in sublime, i got this

![image](https://user-images.githubusercontent.com/627278/91693823-cec6a200-eb95-11ea-818e-920aa257fb25.png)

**Comment by curbengh** [comment]
That's what I suspect would happen as I might've saved with incorrect encoding. Can you try the [original attachment](https://github.com/hexojs/hexo-migrator-wordpress/issues/105#issuecomment-683415042) (which I copied the invalid characters from) and look for L20136 and L25599.

**Comment by tuananh** [comment]
never mind found those char in the original attachment. lemme take a look

**Comment by curbengh** [comment]
Thanks for the info, I'll sanitize the input with `const xml = input.replace(/[\x00-\x09|\x0b-\x0c|\x0e-\x1f]/g, '')`.
