### ISSUE TITLE
Problem running on IBM Bluemix node.js application

### ISSUE THREAD

**Issue by BenediktKrueger** [tuananh/camaro#12]
I am trying to install the package on Bluemix node.js application without success. See error message below: 
![image](https://user-images.githubusercontent.com/15983365/29946101-4d1a6fee-8ea4-11e7-928f-fdb64ef44121.png)

**Comment by tuananh** [comment]
looks like the server is missing `libstdc++6`. i'm not familiar with Bluemix but looks like you cannot install any additional library on it right?
