### ISSUE TITLE
Can't extract namespaces from document root

### ISSUE THREAD

**Issue by marcolarosa** [tuananh/camaro#147]
First up - thanks for this! I've had the unfortunate displeasure of having to deal with XML at various times in the past and this is the nicest way of working with it I've ever seen!

**Describe the bug**
I'm not sure it's a bug because the lib works fine with elements under the root. But given:

```
let ontology = `
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE rdf:RDF [
            <!ENTITY gist "https://w3id.org/semanticarts/ns/ontology/gist/">
            <!ENTITY gistd "https://w3id.org/semanticarts/ns/data/gist/">
            <!ENTITY owl "http://www.w3.org/2002/07/owl#">
            <!ENTITY rdf "http://www.w3.org/1999/02/22-rdf-syntax-ns#">
            <!ENTITY rdfs "http://www.w3.org/2000/01/rdf-schema#">
            <!ENTITY skos "http://www.w3.org/2004/02/skos/core#">
            <!ENTITY xsd "http://www.w3.org/2001/XMLSchema#">
        ]>
        <rdf:RDF
            xmlns:gist="https://w3id.org/semanticarts/ns/ontology/gist/"
            xmlns:gistd="https://w3id.org/semanticarts/ns/data/gist/"
            xmlns:owl="http://www.w3.org/2002/07/owl#"
            xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
            xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
            xmlns:skos="http://www.w3.org/2004/02/skos/core#"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema#"></rdf:RDF>
        `;

```

(In my testing it fails with the full document as well - this is just a simplified version of it)

And template: 
```JS
let namespaces = [
        "/rdf:RDF",
        {
            "gist": "@xmlns:gist"
        }
    ],

```

And the code:
```JS
 const namespaces = await transform(ontology, namespaces);
 console.log(namespaces);
```

Gives: `[ { gist: '' } ]`

**Expected behavior**

Expected output: `[ { gist: 'https://w3id.org/semanticarts/ns/ontology/gist/' } ]`

**Screenshots**

- camaro version: 6.2.3 
- Node version: v20.11.1
- Operating system: MacOS Sonoma 14.5

**Comment by tuananh** [comment]
@marcolarosa it looks like i have asked upstream library about this before and it's not supported 

https://github.com/zeux/pugixml/issues/168

**Comment by marcolarosa** [comment]
ok thanks!
