### ISSUE TITLE
How to define namespaces?

### ISSUE THREAD

**Issue by axelpale** [tuananh/camaro#16]
If my XML document contains identical local tag names but in different namespaces, how to tell camaro to select only the other? For example consider the following:

    <?xml version="1.0" encoding="UTF-8"?>
    <bookings>
      <restaurant xmlns="http://mycustom/namespace">
        <table>
          <reserved>1</reserved>
        </table>
      </restaurant>
      <restaurant xmlns="http://official/namespace/1.2">
        <name>Pizzeria Piccolo</name>
        <table>
          <forPersons>4</forPersons>
          <reserved>
            <from>2017-12-12T16:40</from>
            <to>2017-12-12T18:40</to>
          </reserved>
        </table>
      </restaurant>
    </bookings>

How to select only the tables in the namespace `http://official/namespace/1.2`?

With XPath, one typically defines which prefix maps to which namespace, for example:

    {
      c: 'http://mycustom/namespace',
      o: 'http://official/namespace/1.2'
    }

And then the template to match the official tables becomes:

    var template = {
      tables: ['//o:table', {
        reserved: 'o:reserved'
      }]
    };

The example is of course made up and lacking but still, is it possible to do this in camaro?

**Comment by tuananh** [comment]
@axelpale it seems to be a limitation of pugixml, a library which camaro is built on. lemme check with the author of pugixml to see if there's workaround for this.

**Comment by tuananh** [comment]
@axelpale you can try this

```
const transform = require('camaro')

const xml = `
<?xml version="1.0" encoding="UTF-8"?>
<bookings>
    <restaurant xmlns="http://mycustom/namespace">
        <table>
            <reserved>1</reserved>
        </table>
    </restaurant>
    <restaurant xmlns="http://official/namespace/1.2">
        <name>Pizzeria Piccolo</name>
        <table>
            <forPersons>4</forPersons>
            <reserved>
                <from>2017-12-12T16:40</from>
                <to>2017-12-12T18:40</to>
            </reserved>
        </table>
        <table>
            <forPersons>2</forPersons>
            <reserved>
                <from>2018-12-12T16:40</from>
                <to>2018-12-12T18:40</to>
            </reserved>
        </table>
    </restaurant>
</bookings>
`
const result = transform(xml, {
    nodes: [
        '//restaurant[namespace-uri() = "http://official/namespace/1.2"]/table',
        {
            forPersons: 'forPersons',
            from: 'reserved/from',
            to: 'reserved/to'
        }
    ]
})

console.log(JSON.stringify(result, null, 4))
```

**Comment by axelpale** [comment]
@tuananh Oh, thanks! It was possible after all. I think this issue can now be closed. Would you accept a pull request where I have extended README.md to document this feature?

**Comment by tuananh** [comment]
Sure. PRs are welcome.
