### ISSUE TITLE
Issue in Loading camaro on AWS Lambda

### ISSUE THREAD

**Issue by veeaarr** [tuananh/camaro#18]
I am trying to load Camaro module on my app, it works fine locally (Node v8). But when deploying on AWS Lambda (Node v6.10 runtime) it breaks. Is this library limited to later version of Node. If yes, can you please share how to build this for a lower Node version.

Thanks.

**Comment by tuananh** [comment]
did you copy the `node_modules` from your local machine and upload to lambda?

you will have to use a compiled version of camaro that built on linux with node 6 (since lambda only supports up to node 6 right).

Please find it in [Releases](https://github.com/tuananh/camaro/releases)

**Comment by veeaarr** [comment]
Thanks for your reply. I included the compiled camaro.node  into the node_modules folder. It loads alright. But when invoking the method, it says - 'transform is not a function'. The same used to work when importing the source directly.

![image](https://user-images.githubusercontent.com/10072032/32072219-831bd204-baaf-11e7-986d-fe5a2e900d10.png)

**Comment by tuananh** [comment]
did you put it in `camaro/lib/binding/camaro.node` ?

**Comment by tuananh** [comment]
alternatively, you can spun up an instance similar to what they used in aws lambda and install camaro there. copy the module folder back :D

**Comment by veeaarr** [comment]
Moved the compiled binary to camaro/lib/binding/camaro.node and it worked like a charm. Thanks again.

**Comment by tuananh** [comment]
Glad it's working for you. I've update the readme to include this https://github.com/tuananh/camaro#using-camaro-on-aws-lambda

**Comment by tbrannam** [comment]
Are there any requirements to deploy `node-pre-gyp` similarly?  
Should one expect this to work with Webpack?

```
Unable to import module 'index': Error
    at webpackEmptyContext (/var/task/index.js:20451:10)
    at Object.module.exports../node_modules/node-pre-gyp/lib/pre-binding.js.exports.find (/var/task/index.js:21328:91)
    at Object../node_modules/camaro/index.js (/var/task/index.js:2628:28)
    at __webpack_require__ (/var/task/index.js:21:30)
    at Object../src/helloWorld/transformers/index.ts (/var/task/index.js:35195:34)
    at __webpack_require__ (/var/task/index.js:21:30)
    at Object../src/helloWorld/services/parentvue.ts (/var/task/index.js:34950:24)
    at __webpack_require__ (/var/task/index.js:21:30)
    at Object../src/helloWorld/parentvue.ts (/var/task/index.js:34843:21)
    at __webpack_require__ (/var/task/index.js:21:30)
```

**Comment by tuananh** [comment]
@tbrannam camaro is a native module atm and it will not work for the web. at least, until I can have time to figure out how to compile it to webassembly.

**Comment by tbrannam** [comment]
I didn't give enough context in my question.  I was using webpack to just generate a single JS file and deploying to lambda.

**Comment by tuananh** [comment]
@tbrannam you're just using camaro to generate the js file and will only deploy that js file to lambda ? in that case, it should be fine for this purpose.
