### ISSUE TITLE
Browser compatibility?

### ISSUE THREAD

**Issue by xtuc** [tuananh/camaro#21]
Ref https://github.com/Rich-Harris/packd/issues/33

Is your library meant to be distributed/used on the browser as well?

**Comment by tuananh** [comment]
camaro will not work on browser right now because it's written in c++
I'm looking into possibly of this with web assembly

**Comment by xtuc** [comment]
Ok thanks.

You can close this, I was asking for @AlanBreck.

**Comment by tuananh** [comment]
camaro should work in browser now.
