### ISSUE TITLE
Issue Camaro and Lambda AWS / Serverless

### ISSUE THREAD

**Issue by ElviraCB** [tuananh/camaro#22]
Hello, I'm new to using camaro and Lambda function from AWS. When I want to deploy the lambda function with serverless I'm getting the following error in the cloudwatch:
`module initialization error: Error
at Error (native)
at Object.Module._extensions..node (module.js:597:18)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (/var/task/node_modules/camaro/index.js:4:16)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)`

My package.json
`{
  "name": "lambda-dashboardcb",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "nodemon ./bin/www"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "axios": "^0.17.1",
    "body-parser": "^1.18.2",
    "camaro": "^2.2.2",
    "cookie-parser": "^1.4.3",
    "debug": "~2.6.9",
    "express": "^4.15.5",
    "google-oauth-jwt": "^0.2.0",
    "googleapis": "^23.0.0",
    "morgan": "^1.9.0",
    "pug": "^2.0.0-beta11",
    "serve-favicon": "^2.4.5",
    "serverless-http": "^1.5.2"
  },
  "devDependencies": {
    "nodemon": "^1.13.3",
    "serverless-offline": "^3.16.0"
  }
}
`

**My serverless.yml**
service: lambda-dashboardcb

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-1

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
plugins:
  -  serverless-offline

**Comment by tuananh** [comment]
i'm not sure how serverless package your lambda function. does it use the build the zip file for you?
if so, does it use the correct camaro binary that required by lambda?

https://github.com/tuananh/camaro#using-camaro-on-aws-lambda
