### ISSUE TITLE
Could it be it doesn't work on Wíndows?

### ISSUE THREAD

**Issue by PhlppKnst** [tuananh/camaro#28]
Hi,
I am already trying for hours to parse something on windows but the results are not consistent.
It always worked before when I am only extracting one value from an xml, but when I am trying more complex stuff things seem not to work so well,
```javascript
const transform = require('camaro')

const xml = `
<?xml version="1.0" encoding="UTF-8"?>
<bookings>
    <restaurant>
        <name>Pizzeria Piccolo</name>
        <table>
            <forPersons>4</forPersons>
            <reserved>
                <from>2017-12-12T16:40</from>
                <to>2017-12-12T18:40</to>
            </reserved>
        </table>
        <table>
            <forPersons>2</forPersons>
            <reserved>
                <from>2018-12-12T16:40</from>
                <to>2018-12-12T18:40</to>
            </reserved>
        </table>
    </restaurant>
</bookings>
`
const result = transform(xml, {
    nodes: [
        '//restaurant/table',
        {
            forPersons: 'forPersons',
            from: 'reserved/from',
            to: 'reserved/to'
        }
    ]
})

console.log(JSON.stringify(result, null, 4))
```
I get 

`{
    "nodes": []
}`

What am I doing wrong?

Windows 7
camaro 2.26
node 8.7.0

Best,
P

**Comment by tuananh** [comment]
Very weird indeed. I don't have access to a Windows machine. All the tests for Windows are ran by AppVeyor.

Trying your code on [RunKit](https://npm.runkit.com/camaro) yields the correct result (they probably use linux)

![image](https://user-images.githubusercontent.com/627278/36822345-30404e74-1d2a-11e8-919a-664b027571bc.png)

**Comment by tuananh** [comment]
Btw, is your Windows 64bit or 32bit? Does it use the prebuilt binary?

There will be sth like `installed from remote ...` when install if it's using prebuilt binary

**Comment by PhlppKnst** [comment]
I hope this console print helps. I don't really have much knowledge about the npm, but for me it looks like that a prebuilt binary is used.
BTW I have 64bit Windows.

Best,
P
```
node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
node-pre-gyp verb cli   'D:\\Prototyp\\prototypeServer\\TalkToBT\\server\\node_modules\\camaro\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@0.6.39
node-pre-gyp info using node@8.7.0 | win32 | x64
node-pre-gyp verb command install []
node-pre-gyp info check checked for "D:\Prototyp\prototypeServer\TalkToBT\server\node_modules\camaro\lib\binding\camaro.node" (not found)
node-pre-gyp http GET https://github.com/tuananh/camaro/releases/download/2.2.6/camaro-v2.2.6-node-v57-win32-x64.tar.gz
node-pre-gyp http 200 https://github.com/tuananh/camaro/releases/download/2.2.6/camaro-v2.2.6-node-v57-win32-x64.tar.gz
node-pre-gyp info install unpacking camaro.node
node-pre-gyp info tarball done parsing tarball
[camaro] Success: "D:\Prototyp\prototypeServer\TalkToBT\server\node_modules\camaro\lib\binding\camaro.node" is installed via remote
node-pre-gyp info ok
```

**Comment by tuananh** [comment]
I added your script as a test case but all tests passed on AppVeyor (Windows)

https://github.com/tuananh/camaro/blob/feature/check-windows-compatible/test/window.test.js

![image](https://user-images.githubusercontent.com/627278/36893894-4ad1770a-1e3c-11e8-935b-090772525a80.png)

**Comment by madhujsmg** [comment]
I have an windows 64 bit machine and installed  "camaro": "2.1.0" ,same code will work on other OS, even in server also , but it's returning empty array [] from windows machine !!!!!!!

I wondered how it can happen only on windows machine !!!!!

 is that any special configuration required for windows ?

**Comment by tuananh** [comment]
@madhujsmg can you create a PR with a failed test? I tried the above but the test passed on AppVeyor  (windows).

**Comment by davidspiess** [comment]
Tried @PhlppKnst example above with the same empty result 😢 

Win 10x64
Camaro 3.0.3
Node 8.9
MS BuildTools 2015

**Comment by davidspiess** [comment]
Here some more insights:
`result` does actually return something, `JSON.stringify` made an empty array out of it.

```js
{ nodes:
   [ '': { forPersons: '2',
       from: '2018-12-12T16:40',
       to: '2018-12-12T18:40' } ] }
```

**Comment by tuananh** [comment]
@davidspiess many thanks. lemme try those.

**Comment by tuananh** [comment]
so i tried running test directly with `tape`. still green :(

https://ci.appveyor.com/project/tuananh/camaro/build/1.0.364-feature/window-test-fails

**Comment by tuananh** [comment]
@davidspiess thanks. i can make it fail now. lemme investigate more on this.

**Comment by tuananh** [comment]
@davidspiess @PhlppKnst can you try the latest release 3.0.4 now?

**Comment by davidspiess** [comment]
@tuananh awesome work! It works now 🎉🎉

**Comment by tuananh** [comment]
@davidspiess great :)

@madhujsmg it's fixed in https://github.com/tuananh/camaro/commit/6aef2efe93d54399adc49446a388aa4fb2aeb714

I'm closing this now
