### ISSUE TITLE
camaro.transform is not a function

### ISSUE THREAD

**Issue by ianbale** [tuananh/camaro#41]
I've been trying to upgrade camaro on an old app. It's currently using v1.2.0 and working fine. However, there are quite a lot of vulnerabilities reported by npm, so I'd like to update it.

I've already updated some related apps which run on AWS Lambda. I hit issues with v3.0.8 on Lambda, but 3.0.7 is working fine. So I am trying to use the same version for an app that will run on an AWS EC2 linux instance. Locally, it runs on node 8.2.1 on OSX.

When I do a normal install (Locally on OSX): npm i --save camaro@3.0.7 it installs without error, but when it runs, I get this:

```
(node:97402) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3874): TypeError: camaro.transform is not a function
Error saving fare flow data TypeError: camaro.transform is not a function
at transform (/Users/ianbale/Source Code/data-manager-ftp/node_modules/camaro/index.js:34:25)
```

I've also tried rebuilding camaro as I had to do for v1.2.0:

`npm i camaro@3.0.7 --build-from-source --update-binary`

But this fails:

```
285 warn camaro@3.0.7 had bundled packages that do not match the required version(s). They have been replaced with non-bundled versions.
286 verbose stack Error: camaro@3.0.7 install: `node-pre-gyp install --fallback-to-build`
286 verbose stack Exit status 1
286 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
286 verbose stack     at emitTwo (events.js:125:13)
286 verbose stack     at EventEmitter.emit (events.js:213:7)
286 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
286 verbose stack     at emitTwo (events.js:125:13)
286 verbose stack     at ChildProcess.emit (events.js:213:7)
286 verbose stack     at maybeClose (internal/child_process.js:921:16)
286 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
287 verbose pkgid camaro@3.0.7
288 verbose cwd /Users/ianbale/Source Code/data-manager-ftp
289 verbose Darwin 17.6.0
290 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "camaro@3.0.7" "--build-from-source" "--update-binary"
291 verbose node v8.2.1
292 verbose npm  v6.2.0
293 error code ELIFECYCLE
294 error errno 1
295 error camaro@3.0.7 install: `node-pre-gyp install --fallback-to-build`
```

I've also tried simply installing 3.0.7 then overwriting camaro.node with the prebuilt binary camaro-v3.0.7-node-v57-darwin-x64.tar.gz

I get the same runtime error:

```
(node:97402) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3874): TypeError: camaro.transform is not a function
Error saving fare flow data TypeError: camaro.transform is not a function
at transform (/Users/ianbale/Source Code/data-manager-ftp/node_modules/camaro/index.js:34:25)
```

Can you offer any insight into why I am having so much difficulty with this version of Camaro?

**Comment by tuananh** [comment]
can you post the code here?

**Comment by ianbale** [comment]
Code is exactly the same as I was using with v1.2.0

It's a big app, but the relevant part is:

```
const xmlParser = require('camaro')

const templates = {

  flows : {
    flows : ['F',{

      a : "@i",
      o : "@o",
      d : "@d",
      r : "@r",

      f : ['T/FF',{
        c : '../@t',
        s : '@f', 
        i : '@k', 
      }], 
    }],
  },
}

const data = `<F i="A" r="01000" o="1727" d="1867">
    <T t="SDS">
        <FF u="991231" f="170815" k="05YC" fm="00001"/>
    </T>
    <T t="SDR">
        <FF u="991231" f="170815" k="05YB" fm="00001"/>
    </T>
    <T t="7DS">
        <FF u="991231" f="180109" s="100000" k="05X4" fm="00001"/>
    </T>
    <T t="CDR">
        <FF u="991231" f="170815" k="05X9" fm="00001"/>
    </T>
</F>`

let jsonData = xmlParser(data, template)
```

I've reverted back to v1.2.0 and it's working fine again.

Since I posted I've also tried installing 3.0.7 on the EC2 instance in case I got a different result to that on my local Mac. It was the same.

I'm wondering if there is some sort of clash with one of the other libraries I am using...? Here's my dependencies:

```
 "dependencies": {
    "app-root-dir": "^1.0.2",
    "async-sequence": "^2.0.3",
    "aws-sdk": "^2.251.1",
    "camaro": "^1.2.0",
    "crypto": "^1.0.1",
    "graceful-fs": "^4.1.11",
    "https": "^1.0.0",
    "line-by-line": "^0.1.5",
    "lodash": "^4.17.10",
    "mkdirp": "^0.5.1",
    "moment": "^2.22.2",
    "node-schedule": "^1.3.0",
    "pump": "^3.0.0",
    "rimraf": "^2.6.2",
    "s3": "^4.4.0",
    "serialize-error": "^2.1.0",
    "sprintf": "^0.1.5",
    "ssh2": "^0.4.15",
    "ssh2-sftp-client": "^2.0.1",
    "ssh2-streams": "^0.1.19",
    "stat-mode": "^0.2.2",
    "tmp": "0.0.33",
    "unzipper": "^0.8.9"
  },
```

**Comment by tuananh** [comment]
i tried your code on my Mac (node 8) and it's working fine :-s

**Comment by ianbale** [comment]
Same code works fine in my Lambda functions...

Do you have any idea what might be causing that runtime error? (camaro.transform is not a function)

**Comment by tuananh** [comment]
it's probably something wrong with the binary

https://github.com/tuananh/camaro/blob/develop/index.js#L34

**Comment by ianbale** [comment]
Wrong binary?

I tried updating the binary : npm i camaro@3.0.7 --build-from-source --update-binary
which gives the above errors. Any idea why I can't build 3.0.7? It works just fine for v1.2.0, so it seems like my environment is setup properly for building...?

And tried downloading the pre-built binary : camaro-v3.0.7-node-v57-darwin-x64.tar.gz
That's the right one for node 8.2.1 on OSX isn't it?

**Comment by tuananh** [comment]
why do you need `--build-from-source` and `--update-binary` btw?

when i test on my machine, this is what i get


```
npm i camaro@3.0.7

> camaro@3.0.7 install /Users/anh/code/test/node_modules/camaro
> node-pre-gyp install --fallback-to-build

[camaro] Success: "/Users/anh/code/test/node_modules/camaro/lib/binding/camaro.node" is installed via remote
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.

+ camaro@3.0.7
updated 1 package in 5.718s
```

**Comment by ianbale** [comment]
If I do (after removing the existing version)
`npm i camaro@3.0.7 `
I get this:

```
> camaro@3.0.7 install /Users/ianbale/Source Code/data-manager-ftp/node_modules/camaro
> node-pre-gyp install --fallback-to-build

[camaro] Success: "/Users/ianbale/Source Code/data-manager-ftp/node_modules/camaro/lib/binding/camaro.node" is installed via remote
**npm WARN camaro@3.0.7 had bundled packages that do not match the required version(s). They have been replaced with non-bundled versions.**

+ camaro@3.0.7
added 113 packages from 48 contributors and audited 249 packages in 5.755s

```

Then when I run the function I get camaro.transform is not a function.

**Comment by ianbale** [comment]
> why do you need --build-from-source and --update-binary btw?

I only need this when running on AWS EC2. I don't do that locally on my Mac.

**Comment by tuananh** [comment]
hmm, you got a line different with mine

**npm WARN camaro@3.0.7 had bundled packages that do not match the required version(s). They have been replaced with non-bundled versions.**

i have no idea what that means though

**Comment by ianbale** [comment]
My suspicion is that one of my dependencies has a different version to one that either camaro has, or one of its dependencies and the one that gets used is not compatible with camaro. Most likely, I have  newer version of something. Would be nice if it gave an actual list of what was updated rather than just a count...

I'll double check if there is anything in my list that I no longer need (possible as I have reworked this a bit), then go through camaro's dependencies / dependencies dependencies etc. and see if I can find which one is causing the problem. I'll let you now what I find. 

Thanks for taking the time to look at this for me.

**Comment by tuananh** [comment]
My sincere condolences to you and your family. May your father rest in
peace.

**Comment by tuananh** [comment]
Closing with https://github.com/tuananh/camaro/pull/64

**Comment by mackongo** [comment]
Hi there! was this sorted? I still get this on 6.0.3

**Comment by tuananh** [comment]
> 
> 
> Hi there! was this sorted? I still get this on 6.0.3

can you share your setup. OS/node/npm version and a minimal script to reproduce the error.

**Comment by mackongo** [comment]
6.14.7 npm
v14.5.0 node

Running on Ubuntu 18.04 bionic | on AWS ec2

**Comment by tuananh** [comment]
> 
> 
> 6.14.7 npm
> v14.5.0 node
> 
> Running on Ubuntu 18.04 bionic | on AWS ec2

can you upload teh code snippet to reproduce this error?
