### ISSUE TITLE
Look into possibility use of wasm

### ISSUE THREAD

**Issue by tuananh** [tuananh/camaro#45]
may get some performance hit but good for those who doesn't want to deal with prebuilt binaries.

**Comment by axelpale** [comment]
+1. Compatibility over efficiency!

**Comment by tuananh** [comment]
update: got it working in browser now. I'm gonna finishing up the example, benchmark and do an alpha release

![image](https://user-images.githubusercontent.com/627278/57849550-bf3b1280-7805-11e9-8c9f-1db679a7f2d6.png)

**Comment by tuananh** [comment]
Closing with https://github.com/tuananh/camaro/pull/64
