### ISSUE TITLE
How are XML attributes stored in the json object?

### ISSUE THREAD

**Issue by simonwjackson** [tuananh/camaro#5]
I didn't see an example in the docs. 
Do you use the '$' property like the other `xml-> json` libraries?

**Comment by tuananh** [comment]
You can use `@` as specify in XPath documentation to get the attribute. camaro do not parse all automatically but only what in the template that you pass to camaro

const transform = require('camaro')

```
const xml = `
<xml>
    <person name="john"/>
    <person name="jane"/>
    <person name="dave"/>
    <person name="james"/>
</xml>
`
const result = transform(xml, {
    names: ['//person', '@name']
})

console.log(JSON.stringify(result, null, 2))
```

Will give you

```
{
  "names": [
    "john",
    "jane",
    "dave",
    "james"
  ]
}
```
