### ISSUE TITLE
npm installation failed

### ISSUE THREAD

**Issue by measaperson** [tuananh/camaro#58]
When I try to install your module using `npm install camaro` I get this error

> camaro@3.0.15 install c:\....\node_modules\camaro
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://github.com/tuananh/camaro/releases/download/3.0.15/camaro-v3.0.15-node-v57-win32-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for camaro@3.0.15 and node@8.11.1 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=c:\\...\\node_modules\\camaro\\lib\\binding\\camaro.node" "--module_name=camaro" "--module_path=c:\\...\\node_modules\\camaro\\lib\\binding" "--napi_version=1" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v57"
gyp ERR! cwd c:\...\node_modules\camaro
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=c:\...\node_modules\camaro\lib\binding\camaro.node --module_name=camaro --module_path=c:\...\node_modules\camaro\lib\binding --napi_version=1 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (c:\...\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Windows_NT 10.0.17763
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "c:\\...\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd c:\...\node_modules\camaro
node-pre-gyp ERR! node -v v8.11.1
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=c:\…\node_modules\camaro\lib\binding\camaro.node --module_name=camaro --module_path=c:\...\node_modules\camaro\lib\binding --napi_version=1 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)
npm WARN sip No description
npm WARN sip No repository field.
npm WARN sip No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! camaro@3.0.15 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the camaro@3.0.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\...\AppData\Roaming\npm-cache\_logs\2019-02-22T12_21_50_074Z-debug.log

I will attach the log file

[2019-02-22T12_21_50_074Z-debug.log](https://github.com/tuananh/camaro/files/2893946/2019-02-22T12_21_50_074Z-debug.log)

**Comment by tuananh** [comment]
@measaperson can you try 3.0.14 build. I will take a look at why prebuild binary for 3.0.15 wasn't published

**Comment by tillsimo** [comment]
Hi, got the same error. But worked with the 3.0.14 version.
TS

**Comment by tuananh** [comment]
Noted. I did some changes recently and somehow it messed up , results in binary not publised

**Comment by ahavriluk** [comment]
3.0.14 didn't work for me. We can't download anything to a build box.

**Comment by ahavriluk** [comment]
Is it possible to install Camaro without downloading anything from internet?

**Comment by tuananh** [comment]
@ahavriluk yes it is possible. but you will have to setup what's required by node-gyp because camaro is using node-gyp to build from source

https://github.com/nodejs/node-gyp

**Comment by aambega2** [comment]
@tuananh can you please provide some steps to install Camero using node-gyp. thanks!

**Comment by tuananh** [comment]
@aambega2 I suppose you mean you want to install from source using node-gyp?

you can see the requirement for each platform here

https://github.com/nodejs/node-gyp#installation

**Comment by tuananh** [comment]
Closing with https://github.com/tuananh/camaro/pull/64
