### ISSUE TITLE
x86_64 binaries are compiled for a specific arch?

### ISSUE THREAD

**Issue by rumblesnort** [tuananh/camaro#60]
Hello,

When our developers are trying to install camaro via NPM the binaries being downloaded give an "Illegal Instruction" on Westmere generation chips.

Are you compiling with a specific -march flag?  Considering there are many generations of Xeons in production everywhere is it possible to get a less processor-specific build included in npm to make it easier to install?  

I get the need to tweak for speed, and if we need to we can compile this for a particular generation of processors using specific versions of GCC/Clang we can, but it may be a good idea to make it 'just work' for older x86_64 builds?

**Comment by tuananh** [comment]
@rumblesnort you can always do `npm install --from-source --update-binary` to force it to compile from source? Does it work for you?

**Comment by rumblesnort** [comment]
Hey Tuananh,

Thank you for responding.  That does work, yes, but:

-  requires us to install build tools on production systems (in this case, Alpine/Docker) that don’t support the instruction your compiler is using for the binary
-  complicates the docker build file
-  most Node developers aren’t C developers; likely aren’t familiar with building and would have a hard time troubleshooting

Not asking that you do a -mtune=pentiumpro or something, maybe westmere or keeping generic?  Your node module is quite popular here, not just for speed but for your approach via Path.  People don’t understand why it doesn’t ‘just work’ on staging/production systems and it does on their Macs.

Are you seeing that much of a difference with specific compiler tuning like this?  With everything being 8+ cores, 32G of memory, 3.5Ghz, etc, etc, I’m not sure how much of an improvement that makes anymore.

**Comment by tuananh** [comment]
I'm not sure which flag is causing problem for you. you can see all the flags i have here

https://github.com/tuananh/camaro/blob/develop/binding.gyp

**Comment by rumblesnort** [comment]
Hey Tuan, it would be this:

-march=native

From the GCC docs:  "This selects the CPU to generate code for at compilation time by determining the processor type of the compiling machine. Using -march=native enables all instruction subsets supported by the local machine (hence the result might not run on different machines). Using -mtune=native produces code optimized for the local machine under the constraints of the selected instruction set."

**Comment by tuananh** [comment]
@rumblesnort i did another release. can you see if it fixes the issue for you.

**Comment by rumblesnort** [comment]
Will do.  Do you need access to an arm server or want arm builds?

**Comment by rumblesnort** [comment]
Tuan - it worked great, thank you!  

richf-alpine:~/eek$ npm install camaro

> camaro@3.0.16 install /home/richf/eek/node_modules/camaro
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download
[camaro] Success: "/home/richf/eek/node_modules/camaro/lib/binding/camaro.node" is installed via remote
npm WARN saveError ENOENT: no such file or directory, open '/home/richf/eek/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/richf/eek/package.json'
npm WARN eek No description
npm WARN eek No repository field.
npm WARN eek No README data
npm WARN eek No license field.

+ camaro@3.0.16
added 68 packages from 65 contributors and audited 97 packages in 2.633s
found 0 vulnerabilities

richf-alpine:~/eek$ cp /tmp/test.js .
richf-alpine:~/eek$ node ./test.js
{ data: 'some-value' }
richf-alpine:~/eek$
————————
richf-alpine:~/eek$ cat /proc/cpuinfo
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 44
model name	: Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz
stepping	: 2
microcode	: 0x1
cpu MHz		: 2666.760
cache size	: 16384 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 11
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes hypervisor lahf_lm pti tsc_adjust arat
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf
bogomips	: 5333.52
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:
