### ISSUE TITLE
Transforming into array without object inside

### ISSUE THREAD

**Issue by devsdevsdevs** [tuananh/camaro#73]
I want to transform an area of an XML document formatted like this:
`<people>
<item>Joseph</item>
<item>Frederick</item>
<item>Kennedy</item>
</people> `
into JSON like so:
`...
people: ["Joseph", "Frederick", "Kennedy"],
...
`
But the only samples I have found only format the template string so it produces an array with an object inside. Is there any way to get a flat array such as the one above?

**Comment by tuananh** [comment]
```
const { transform } = require('camaro')

const xml = "<people> <item>Joseph</item> <item>Frederick</item> <item>Kennedy</item> </people>"

;(async function () {
  console.log(await transform(xml, {
    people: ['/people/item', '.']
  }))
})();
```

output

```
{ people: [ 'Joseph', 'Frederick', 'Kennedy' ] }
```

**Comment by tuananh** [comment]
Feel free to re-open if that is not what you're looking for
