### ISSUE TITLE
implement toJson()

### ISSUE THREAD

**Issue by tuananh** [tuananh/camaro#79]

**Comment by samuil4** [comment]
Hi, I tried to test the toJson 
```
import { toJson } from 'camaro';

toJson(myXMLString)
```

and got compile error 
```
This dependency was not found:

* worker_threads in ./node_modules/piscina/dist/src/index.js

To install it, you can run: npm install --save worker_threads
```

**Comment by tuananh** [comment]
@samuil4 oh yeah. Its not yet implemented. Also camaro requires node version >=12

**Comment by samuil4** [comment]
@tuananh thanks for the info.

**Comment by tuananh** [comment]
I wrote another library for SAX parsing at https://github.com/tuananh/sax-parser so I probably won't fix this
