### ISSUE TITLE
Problem running under docker?

### ISSUE THREAD

**Issue by ianbale** [tuananh/camaro#8]
Hi,

I have a small app which is using camaro. All works fine locally (OSX -  i5 CPU). I recently tried out docker and have moved it into a docker file. I had to remove and reinstall camaro for it to run, but having done that it works perfectly.

Now I've moved my docker image onto a Centos 7 VM (Xeon CPU). Now I'm getting "Illegal instruction (core dumped)" when the app attempts to decode some XML with camaro.

I'm using the official node.js docker image with node v6.11.0

Wondering if this is a known issue and whether there is anything I can do to correct it?

**Comment by tuananh** [comment]
i had issue with the official node alpine image as well. I haven't figured out what's wrong with that yet. I remote login to the docker and recompile and it works again. Is this same as yours?

My current work around is using it with `bitnami/node` Docker image. Maybe give it a try?

**Comment by tuananh** [comment]
Update: Just found out one of my apps use camaro with `node:boron` image as well. Nothing special about that Dockerfile. 😕

**Comment by tuananh** [comment]
Can you check gcc version? camaro requires gcc 4.9 or newer.

**Comment by tuananh** [comment]
@ianbale weird indeed. we have test system using `FROM bitnami/node:8.1.3-r0` and another one using `node:boron`. those images work fine.

**Comment by tuananh** [comment]
btw, can you post your dockerfile here?

**Comment by ianbale** [comment]
As I mentioned, the official node image works just fine when it's on my iMac. It just doesn't run on my VM server in the Centos VM. I just tried creating a Debian 9 VM instead. Not sure what I've done wrong, but I just get a black screen in boot! Most annoying... Will retry later and let you know how I get on.

**Comment by ianbale** [comment]
I've given it a try on Debian 9. I just tried it installing node into the host, rather than try docker. I get the exact same error: illegal instruction when node tries to use camaro.

This VM has gcc version 6.3.0

Do you think the problem is stemming from the CPU of the system this VM is running on? I'm using XenServer on a machine with two Xeon 5520 (quad core) CPUs.

You mentioned something about recompiling camaro. I winder if that might help since gcc on the machine should produce code it can run... How would I go about doing that?

As a small aside, I'm tying to use the XPath replace command (type : 'replace(@type, "([^.]+)$", "$1")',) but it doesn't seem to work. No matter what I put in the replace, the output is always an empty string. Even something as simple as replace('bob','b','*') which out to result in *o*. ANy idea why that might not be working?

**Comment by ianbale** [comment]
As a small aside, I'm tying to use the XPath replace command (type : 'replace(@type, "([^.]+)$", "$1")',) but it doesn't seem to work. No matter what I put in the replace, the output is always an empty string. Even something as simple as replace('bob','b','*') which out to result in *o*. Any idea why that might not be working?

On that note... Is this something you are actively developing? Ot just something you needed and have decided to share with the world? If the former, then I have a few suggestions for enhancements that could be really useful...

**Comment by tuananh** [comment]
> You mentioned something about recompiling camaro. I winder if that might help since gcc on the machine should produce code it can run... How would I go about doing that?

You will have to do that at run time rather than in Dockerfile because otherwise, Docker will do that when building image.

> XPath replace command (type : 'replace(@type, "([^.]+)$", "$1")',)

Where did you find this command? I couldn't find it here https://developer.mozilla.org/en-US/docs/Web/XPath/Functions

pugixml which camaro depends on, implements xpath 1.0 (latest is 2 i think) so there might be some limitations which functions are available.

> Is this something you are actively developing? Ot just something you needed and have decided to share with the world?

It's just something I built out of frustration at work but your ideas are welcome.

**Comment by ianbale** [comment]
Ah! Yes, replace is an xpath 2.0 function. That explains why that is not working...

Right now I'm not so bothered about docker. My main goal is to get it to work with node running natively under a VM on my production server. At the moment, I'm just getting the illegal instruction.

I believe that this is due to pugixml rather than camaro. I don't understand how you've bundled pugixml into camaro, but I suspect that the bundled version is incompatible with my server (and I can only assume because of the CPU since gcc libs are correct and I've tried more than one OS). Is it possible to bundle a different version into it? One compiled on the server which should then work ok... If so, how can I do that?

In terms of some ideas, I'm not so sure what scope you might have with pugi using xpath1. But I could do with some conditional logic.

eg. My XML might look like this:
 <Leg>
    <TimetableLeg>
         <a>xxx</a>
     </TimethableLeg>
 </Leg>
 <Leg>
    <TimetableLeg>
         <a>xxx</a>
     </TimethableLeg>
 </Leg>
 <Leg>
    <FixedLeg>
        <b>yyy</b>
     </FixedLeg>
</Leg>

Now I can do something like this:

		legs : ['Leg',{
			a : 'TimetableLeg/a',
			b : 'FixedLeg/b',
		}],

And I'll end up with:

legs : [
 {
     a : 'xxx',
     b : ''
  },
 {
     a : 'xxx',
     b : ''
  },
 {
     a : '',
     b : 'yyy'
  },
]

What I'd like is :

legs : [
 {
     a : 'xxx',
  },
 {
     a : 'xxx',
  },
 {
     b : 'yyy'
  },
]

So I'd need something along the lines of :

		legs : ['Leg',{
                        if (TimetableLeg)
   			    a : 'TimetableLeg/a',
                        else
   			     b : 'FixedLeg/b',
		}],


Although, in this instance, something like this would also suffice :  

		legs : ['Leg',{
			a : 'excludeIfNull(TimetableLeg/a)',
			b : 'excludeIfNull(FixedLeg/b)',
		}],


Essentially, exclude elements from the results where the input cannot be found - rather than return an empty string.

Buy maybe I'm after too much from this. Perhaps I'm better off pre-processing the XML with XSLT, then parsing afterwards...?


It would also be useful to do some sort of manipulation of the string. A regex change would do in most cases, but a custom function would be perfect. eg.

<carType>4</carType>

carType : convertCarTypeIdToName('carType')

So that my output looks like

carType : 'hybrid'

rather than 

carType : 4



I know I can simply map the output and process these lookups afterwards, overwritign the parse output with my translated values. But it would be nice to do it all in one hit as I suspect that this would be faster.

**Comment by tuananh** [comment]
```
legs : [
{
a : 'xxx',
},
{
a : 'xxx',
},
{
b : 'yyy'
},
]
```

For this, i would just use sth like `omit-empty` ; or lodash if you already have it.

```
const omitEmpty = require('omit-empty')
omitEmpty(result)
```

But I might as well make it an option for camaro

**Comment by ianbale** [comment]
Thanks I'll take a look at that.

I've managed to recompile pugi but I'm still getting the same illegal instruction!
My last hope I guess is to recompile the camaro code, but I can't see how to do that...?

Other than that I guess I need to look for another parser which will work on my target system. Very frustrating as outright speed is vital for this project...

**Comment by tuananh** [comment]
I use travis and appveyor to pre build binaries for all platforms. so that users doesn't have to compile on their machine but pulling the prebuilt binaries directly from github releases.

```
npm i camaro --build-from-source --update-binary
```

The above command will ignore it and always build from source instead.

Again, if you could post your Dockerfile or send me via email (me@tuananh.org); I can try debugging with you.

**Comment by ianbale** [comment]
Yay! It's working!!

I'm not sure that sending you the dockerfile will help. I'm 99.99% certain it's got nothing to do with that. I'm pretty certain that it's just a platform issue. The pre-built binaries were not suitable for this instance.

What I can do, if you'd like to have a play and work out why so you can update your release is duplicate my VM and give you access to that.

**Comment by tuananh** [comment]
Glad you found a workaround for that. btw, is this with latest version (1.1.6)?

**Comment by ianbale** [comment]
I had 1.1.3

Didn't realise there was a newer version. I'll give that a whirl too.

I described this problem to a friend who has a lot of experience of docker. He's very intrigued. ants to take a look at the problem too

**Comment by valentinvieriu** [comment]
Here is a `Dockerfile` setup that works very well and it's very lightweight:

``` Dockerfile
FROM node:8.2.1-alpine

# set our node environment, either development or production
# defaults to production, compose overrides this to development on build and run
ARG NODE_ENV=production
ENV NODE_ENV $NODE_ENV

# default to port 80 for node, and 5858 or 9229 for debug
ARG PORT=80
ENV PORT $PORT
EXPOSE $PORT 5858 9229

# check every 30s to ensure this service returns HTTP 200
HEALTHCHECK CMD curl -fs http://localhost:$PORT/healthcheck || exit 1

# install dependencies first, in a different location for easier app bind mounting for local development
WORKDIR /usr/src
COPY package*.json /usr/src/
RUN apk add --no-cache git curl && \
npm set progress=false && \
npm config set depth 0 && \
npm install && \
npm cache clean --force && \
apk del git && \
rm -rf /tmp/* /var/cache/apk/* 
ENV PATH /usr/src/node_modules/.bin:$PATH

# copy in our source code last, as it changes the most
WORKDIR /usr/src/app
COPY . /usr/src/app

# if you want to use npm start instead, then use `docker run --init in production`
# so that signals are passed properly. Note the code in index.js is needed to catch Docker signals
# using node here is still more graceful stopping then npm with --init afaik
# I still can't come up with a good production way to run with npm and graceful shutdown
CMD [ "node", "--harmony", "server.js" ]

```
