### ISSUE TITLE
transform function return undefined (5318992)

### ISSUE THREAD

**Issue by AviramCloudbeat** [tuananh/camaro#80]
Hello,
I'm trying to use camaro in my project and I encounter a problem that I'm not sure where it is coming from.
this is my code:
```     
    const {transform} = require('camaro');
    const fs = require('fs');
     ....
module.myModule= function () {
       try {
           var xml= fs.readFileSync('c:\myPath\file.xml', 'utf-8');
       } catch (err) {
           console.error(err);
       };

       const sampleTemplet = {
         first: "first element",
         second: "second element"
       };
       (async function() {
          try {
              var result = await transform(xml, sampleTemplet);
          } catch (err) {
              console.error(err);
          };
          console.log(result);
        })();

     };
```
the result is that transform return undefined error (with number 5318992)
and I can't figure out why because there is no err.message or err.stack - both return undefined as well.

- camaro version: 4.0.7 
- Node version: 8.14.0
- Operating system: WIN10

**Comment by tuananh** [comment]
can you provide the xml input that cause the error?

**Comment by AviramCloudbeat** [comment]
Ok, so the issue was this:
In my original 'sampleTemplet' there are a few fields some of them are getting their values from functions, one of them returned 'undefined' and so 'transform()' just sent the message to the console.
It was hard for me to detect since the error message was the most generic as it could be.

**Comment by tuananh** [comment]
@AviramCloudbeat if you could send the xml and template, maybe i can debug it and have better error handling implemented

**Comment by tuananh** [comment]
@AviramCloudbeat second is not a valid xpath expression.

if you want to concat, you can do this

```js
const { transform } = require('camaro')

const xml = require('fs').readFileSync('input.xml', 'utf-8')

;(async function() {
    var example =
        "string(//HTTPSamplerProxy[@testname='test1']/stringProp[@name='HTTPSampler.protocol'])"
    const sampleTemplate = { first: example, second: `concat(${example}, ${example})` }

    const result = await transform(xml, sampleTemplate)

    console.log(JSON.stringify(result, null, 2))
})()

```

**Comment by AviramCloudbeat** [comment]
Yes, I understand it now :(
My problem was to locate where the bug is.

**Comment by tuananh** [comment]
> Yes, I understand it now :(
> My problem was to locate where the bug is.

true. i can def. do a better error reporting here.
