### ISSUE TITLE
Publish 3.0.18 to npm and build 3.0.17 win32x64

### ISSUE THREAD

**Issue by dice14u** [tuananh/camaro#88]
**Describe the bug**
Due to the performance decrease in going to webasm I wish to stay at v3 of the package, there are some issues though with the builds of 3.0.17 and 3.0.18,
first is that 3.0.18 has not been sent to the npmjs.org registry (having instead 3.0.17)
second is that 3.0.17 does download and install correctly on win32-x64 devices

node-pre-gyp WARN Tried to download(404): https://github.com/tuananh/camaro/releases/download/3.0.17/camaro-v3.0.17-node-v72-win32-x64.tar.gz

than later camaro\src\transform.cpp(5): fatal error C1083: Cannot open include file: 'pugixml/src/pugixml.hpp': No such file or directory (compiling source file
 ..\src\camaro.cpp) [[...]\camaro\build\camaro.vcxproj] as it seems the dependencies don't get loaded in the build script.

**Comment by tuananh** [comment]
@dice14u i dont have a windows machine to test right now but can you try `npm install camaro@3.0.19`?

**Comment by dice14u** [comment]
As a follow up on this 3.0.19 worked, it compiled well.  I tried using 4.x briefly as well but it seemed there was a greater error rate with "socket hung up" from the results of camaro.transform, so went for the version that stayed a little more stable.
