### ISSUE TITLE
`transform` in parallel does not work and messes with process

### ISSUE THREAD

**Issue by betafcc** [tuananh/camaro#92]
**Describe the bug**

If you call `transform` before it's previous invocation has returned, it seems to drop the previous promise somehow

eg:
```js
const { transform } = require('camaro')

const doit = () => transform('<foo>bar</foo>', { foo: 'foo' })

doit().then(_ => console.log('done 1'), console.error)
doit().then(_ => console.log('done 2'), console.error)
```
output
```
done 2
```

Even weirder, if you force `Promise.all([doit(), doit()])` it seems to mess up with the whole process!

```js
const { transform } = require('camaro')

const sleep = t => new Promise(resolve => setTimeout(resolve, t))

const doit = () => transform('<foo>bar</foo>', { foo: 'foo' })

const main = async () => {
  const sleeper = sleep(3000).then(_ => console.log('done sleeping')) // enqueu before, do run after 3 seconds

  try {
    const r = await Promise.all([doit(), doit()])
  } finally {
    console.log('finally block') // never runs
  }

  await sleeper
  console.log('after awaiting sleeper') // never runs
}

main()
```
This scripts waits 3 seconds to exit but only outputs 'done sleeping'

- camaro version: 4.0.8, 4.1.2
- Node version: v8.16.0, v10.16.0, v12.14.0, v13.5.0
- Operating system: Linux Mint 19.1 Tessa

In camaro `3.0.19` it does work fine

**Comment by tuananh** [comment]
Thanks. Let me take a look at it.

**Comment by tuananh** [comment]
please expect this to take sometimes as i'm having a new newborn baby atm.

or you can try using v3 in the mean time.

i suspect that happens because the way i cache the instance but i'm not sure.

**Comment by betafcc** [comment]
Wow, congrats man :3

I've been using this workaround since then:
```ts
import { transform as unsafeTransform } from 'camaro'

export const locked = <F extends (...a: any[]) => Promise<any>>(f: F): F => {
  let lock = Promise.resolve()

  return (...a) => new Promise((resolve, reject) => {
    lock = lock.then(_ => f(...a).then(resolve, reject))
  })
}

export const transform = locked(unsafeTransform)
```
Just locking the function to only run after the previous invocation has resolved
