### ISSUE TITLE
Node throw error

### ISSUE THREAD

**Issue by vsaran93** [tuananh/camaro#96]
having error in below line (node_modules\camaro\dist\camaro.js:9) in windows 10 (64bit)

if(aa){v=__dirname+"/";var da,ea;w=function(a,b){da||(da=require("fs"));ea||(ea=require("path"));a=ea.normalize(a);a=da.readFileSync(a);return b?a:a.toString()};x=function(a){a=w(a,!0);a.buffer||(a=new Uint8Array(a));a.buffer||z("Assertion failed: undefined");return a};1<process.argv.length&&process.argv[1].replace(/\\/g,"/");process.argv.slice(2);process.on("uncaughtException",function(a){throw a;});process.on("unhandledRejection",z);e.inspect=function(){return"[Emscripten Module object]"}}else if(ca)"undefined"!=

camaro version: 4.1.2
Node version: 12.16.2
OS: Windows 10 (64 bit)

what could be the solution to this error ?

**Comment by tuananh** [comment]
can you post the code that gives you that error?

**Comment by kierangraham** [comment]
Interestingly I ran into this error on a recent project and the reason was passing an _array_ object as the XML template rather than an object. I was creating a test to parse a list of items and ran into this.

The test would have looked something like this (which resulted in the error):
```typescript
  const template = [
      '//category[2]/display-name',
      {
        lang: '@xml:lang',
        text: 'text()',
      },
  ];
  
  const parsed = await transform(testXML, template);
```
> Example with error similar to that noted above

Changing the template code to something like this resulted in a successful parsing:

```typescript
const template = {
    displayName: [
      '//category[2]/display-name',
      {
        lang: '@xml:lang',
        text: 'text()',
      },
    ],
  };

  const parsed = await transform(testXML, template);
```
> Working Example

---

Maybe that is useful.

**Comment by tuananh** [comment]
@kierangraham thanks. The template is array kind of make sense and camaro should support this.

**Comment by tuananh** [comment]
@kierangraham it should work for your use case now.

**Comment by kierangraham** [comment]
@tuananh Great work, thanks for the effort on this!

**Comment by tuananh** [comment]
@vsaran93 feel free to re-open if the issue still persists
